.TH CUPIDWM 1 VERSION
.SH NAME
cupidwm \- source configured X11 tiling window manager
.SH SYNOPSIS
.B cupidwm
.RB [ \-v ]
.SH DESCRIPTION
cupidwm is a small source-configured X11 tiling window manager.
Configuration is done in config.h and requires recompilation.
.SH OPTIONS
.TP
.B \-v
Print version information and exit.
